CREATE TABLE user (
    userID int,
	username varchar(255),
   	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY ( messageID )
);


CREATE TABLE messages (
    messageID int,
    recipientID int,
	recipientString varchar(255),
	senderID int,
	attachmentFlag int,
	replyFlag int,
	forwardFlag int,
    subject varchar(255),
    body varchar(255),
   	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY ( messageID )
);


CREATE TABLE attachments (
    attachmentID int,
    messageID int,
	directoryPath varchar(255),
	date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY ( attachmentID )
);


1. Composing an email 
	When the user press the compose button, the new email box will appear to the right pane. Once the email is finish, from a dropdown select recipient (To) and submitted, data will be
	sent into the database message table.
	
	-mesageID will be autogenerated
	-recipientID will be added. If multiple users, then the function must generate copies of the same message for each user
	-senderID will be added
	-IF ANY, attachment flag will set to 1 (0 is default)
	-Since this is a new composed email, replyFlag must remain in 0
	-Since this is a new composed email, forwardFlag must remain in 0
	